######################################################################
# Automatically generated by qmake (2.01a) dim. janv. 5 18:11:45 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += myDriver.c myDriver.mod.c
